export const FILTER_FIELD = {
  RFQ: "RFQ",
  QUOTE_ID: "QUOTE_ID",
  LAST_UPDATED: "LAST_UPDATED",
  SENDER: "SENDER",
  SUBJECT: "SUBJECT",
  PRODUCT: "PRODUCT",
  PERCENTAGE: "PERCENTAGE",
  QUANTITY: "QUANTITY",
  QUOTE_STATUS: "QUOTE_STATUS",
  MARKET: "MARKET"
};

export const LIST_TYPE = {
  RFQ: "RFQ",
  QUOTE: "QUOTE",
  EXCEPTION: "EXCEPTION"
};

export const LIST_TYPE_MAPPING = {
  0: "RFQ",
  1: "QUOTE",
  2: "EXCEPTION"
}
