export const FILTER_FIELD = {
  RFQ: "RFQ",
  QUOTE_ID: "QUOTE_ID",
  LAST_UPDATED: "LAST_UPDATED",
  SENDER: "SENDER",
  SUBJECT: "SUBJECT",
  PRODUCT: "PRODUCT",
  PERCENTAGE: "PERCENTAGE",
  QUANTITY: "QUANTITY",
  QUOTE_STATUS: "QUOTE_STATUS",
  MARKET: "MARKET"
};
